Algoritmo "conversor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/09/2024
Var
   angulo, S: Real


Inicio
   Escreva ("Informe um angulo: ")
   Leia (angulo)
   S <- Sen(GraupRad (angulo))
   Escreva ("O seno de ", angulo , " é igual a ", S)


Fimalgoritmo