Algoritmo "FunçõesAritméticas"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/09/2024
Var
   angulo, S: real


Inicio
      escreva ("Informe um angulo: ")
      leia (angulo)
      S <- Sen(GraupRad (angulo))
      escreva ("O seno de ", angulo, " é igual a ", S)


Fimalgoritmo