Algoritmo "Operadores Lógicos"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/09/2024
Var
   A, B, C: Inteiro


Inicio
   A <- 2
   B <- 3
   C <- 5
   Escreval (verdadeiro e falso)
   Escreval (verdadeiro e verdadeiro)
   Escreval (falso e falso)
   Escreval  ((A=B) ou (C>A))
   Escreva  (nao((A=B) ou (C>A)))


Fimalgoritmo