Algoritmo "SOMAS"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/09/2024
Var
   N1, N2, S: Inteiro

Inicio
   Escreva ("Informe um número: ")
   Leia (N1)
   Escreva ("Informe outro número: ")
   Leia (N2)
   S <- N1 + N2
   Escreva ("A soma entre ", N1, " e ", N2, " é igual a ", S)
Fimalgoritmo